name: debug-action
inputs: {}
outputs:
  tags-list:
    description: "Latest versions"
    value: ${{ steps.get-versions.outputs.test }}
  tags-list2:
    description: "Latest versions2"
    value: ${{ steps.get-versions2.outputs.test }}
runs:
  using: "composite"
  steps:
    - name: Checkout to repository
      uses: actions/checkout@v3
    - id: get-versions
      shell: bash
      run: echo "test=HelloWorld" >> $GITHUB_OUTPUT
    - id: get-versions2
      shell: pwsh
      run: echo "test= hahaha!" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append

