name: set-environment-variables

description: |
  Sets environment variables in the current job based on a JSON string.

inputs: {}

runs:
  using: 'composite'
  steps:
    - name: Declare variables
      shell: pwsh
      run: |
        $envVars = @{
          VAR1 = 'value1'
          VAR2 = 'value1'
          VAR3 = 'value1'
          VAR4 = 'value1'
          VAR5 = 'value1'
        }
        $envVars.GetEnumerator() | ForEach-Object {"$($_.Key) - $($_.Value)"}
        foreach($var in $envVars){
          Write-Host "V = $var.Key ; Value = $var.Value"
        }
        # To persist the values of env vars, you need to do the following
        foreach($key in $envVars.keys) {
          Write-Host "Setting $key environment variable to value $envVars[$key]"
          echo "$key=$envVars[$key]" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append 
        }
outputs: {}
