name: set-environment-variables

description: |
  Sets environment variables in the current job based on a JSON string.

inputs: {}

runs:
  using: 'composite'
  steps:
    - name: Declare variables
      shell: pwsh
      run: |
        $envVars = @{
          VAR1 = 'value1'
          VAR2 = 'value2'
          VAR3 = 'value3'
          VAR4 = 'value4'
          VAR5 = 'value5'
        }
        $envVars.GetEnumerator() | ForEach-Object {"$($_.Key) - $($_.Value)"}
        # To persist the values of env vars, you need to do the following
        $envVars.GetEnumerator() | ForEach-Object {echo "$($_.Key)= $($_.Value)" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append}
        $foo='foo'
outputs: {}
