name: ShareOutputs
# This example demonstrates the following topics:
# 1. Sharing outputs between jobs
# 2. Setting outputs value using bash shell
# 3. Setting outputs using PowerShell
on: [workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
      output3: ${{ steps.step3.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "test=world" >> $GITHUB_OUTPUT
      - id: step3
        shell: pwsh
        run: echo "test= hahaha!" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
          
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: |
          echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}} ${{needs.job1.outputs.output3}}
      - name: powershell step
        shell: pwsh
        env:
          out1: ${{needs.job1.outputs.output1}}
          out2: ${{needs.job1.outputs.output2}}
          out3: ${{needs.job1.outputs.output3}}
        run: |
          Write-Host "Output1 is: " $Env:out1
          Write-Host "Output2 is: " $Env:out2
          Write-Host "Output3 is: " $Env:out3
        
          
