# This is a basic workflow to help you get started with Actions

name: Test-En-Vars

on: workflow_dispatch

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set environment variables
        uses: ./.github/actions/set-environment-variables

      - name: Consume environment variables with pwsh
        shell: pwsh
        run: |
          Write-Host $foo
          Write-Host "Use env vars from the above step"
          Write-Host "VAR1= "  $Env:VAR1
          Write-Host "VAR2= "  $Env:VAR2
          Write-Host "The values of the env vars are:"
          cat $Env:GITHUB_ENV
          
      - name: Consume environment variables with bash
        shell: bash
        run: |
          echo "This step show how to access the env vars assigned in the previous step"
          echo "${{ env.VAR1 }}" 
          echo "${{ env.VAR2 }}" 
          echo "${{ env.VAR3 }}" 
          echo "${{ env.VAR4 }}"
          echo "${{ env.VAR5 }}"
          echo "${{ env.VAR6 }}"
