# This is a basic workflow to help you get started with Actions

name: Test Config Vars

on: workflow_dispatch

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Test
        uses: ./.github/actions/preprocess-vars

      - name: Consume environment variables with bash
        shell: bash
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer 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"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/tnuvoletta/actions/variables

          echo "This step show how to access the env vars assigned in the previous step in bash shell"
          echo "${{ env.PRINCIPIA_HEADERS_ABSEIL }}" 
          echo "${{ env.PRINCIPIA_MSVC_GOOGLEMOCK }}" 
          echo "${{ env.PRINCIPIA_C_FLAGS }}" 
          echo "${{ env.PRINCIPIA_MSVC_GIPFELI }}"
          echo "${{ env.PRINCIPIA_MSVC_ZFP }}"
          echo "${{ env.PRINCIPIA_UBUNTU_PREREQUISITES }}"
