# This is a basic workflow to help you get started with Actions

name: Test Preprocessing

on: workflow_dispatch

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Test environment variables
        uses: ./.github/actions/preprocess-vars
        
      - name: Consume environment variables with pwsh
        shell: pwsh
        run: |
          Write-Host " List all environment vars in this scope"
          $env | ForEach-Object {
          $name = $_.Key
          $value = $_.Value
          Write-Host "Name = " $name
          Write-Host "Value = " $value
        }
          Write-Host "Use env vars from the above step with PowerShell"
          Write-Host "PRINCIPIA_CLANG_VERSION= "  $Env:PRINCIPIA_CLANG_VERSION
          Write-Host "PRINCIPIA_UBUNTU_PREREQUISITES = "  $Env:PRINCIPIA_UBUNTU_PREREQUISITES

          
      - name: Consume environment variables with bash
        shell: bash
        run: |
          echo "This step show how to access the env vars assigned in the previous step in bash shell"
          echo "${{ env.PRINCIPIA_HEADERS_ABSEIL }}" 
          echo "${{ env.PRINCIPIA_MSVC_GOOGLEMOCK }}" 
          echo "${{ env.PRINCIPIA_C_FLAGS }}" 
          echo "${{ env.PRINCIPIA_MSVC_GIPFELI }}"
          echo "${{ env.PRINCIPIA_MSVC_ZFP }}"
          echo "${{ env.PRINCIPIA_UBUNTU_PREREQUISITES }}"
