name: Test Action Output

on: [workflow_dispatch]
jobs:
  list_tags:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.list-versions.outputs.tags-list }}
    steps:
      - uses: actions/checkout@v3

      - id: list-versions
        uses: ./.github/actions/debug-action
  my_echo:
    runs-on: ubuntu-latest
    needs: list_tags
    steps:
      - name: Echo previous outputs
        run: |
          echo "$OUTPUT1"
        env:
          OUTPUT1: ${{needs.list_tags.outputs.output1}}
