name: test-action-workflow

on: workflow_dispatch

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout
      - name: Set environment variables
        uses: ./.github/actions/set-environment-variables
